language: node_js
node_js:
  - "5"
addons:		 +#addons:
  browserstack:		 +#  browserstack:
    username: "ihorpavlenko1"		 +#    username: "ihorpavlenko1"
    access_key: "uXr97yr9u73mfmRtAyZh"
    forcelocal: true
install:
 - npm install
before_script:
  - http-server -p 8080 & 
  - sleep 3
script:
  - npm run jshint
  - npm run jscs
  - npm run mocha
  - npm run wdio
